scrumlab/urls.py
from django.contrib import admin
from django.urls import path
from jedzonko.views import (
    IndexHtmlView,
    DashboardView,
    RecipesListView,
    RecipeIdView,
    RecipeModify,
    RecipeAdd,
    PlanIdView,
    NewPlan,
    PlanAddRecipe,
    PlansListView,
    Contact,
    AboutApp,
    DeleteRecipeView,

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexHtmlView.as_view()),
    path('main/', DashboardView.as_view(), name='dashboard'),
    path('recipe/<int:id>/', RecipeIdView.as_view(), name='recipe-id'),
    path('recipe/add/', RecipeAdd.as_view(), name='recipe-add'),
    path('recipe/modify/<int:id>', RecipeModify.as_view(), name='recipe-modify'),
    path('recipe/list/', RecipesListView.as_view(), name='recipes-list'),
    path('plan/<int:id>/', PlanIdView.as_view(), name='plan-id'),
    path('plan/add/', NewPlan.as_view(), name='new-plan'),
    path('plan/add-recipe/', PlanAddRecipe.as_view(), name='plan-add-recipe'),
    path('plan/list/', PlansListView.as_view(), name='plan-list'),
    path('delete-recipe/<int:id>/', DeleteRecipeView.as_view(), name='delete-recipe-id'),
    path('edit-plan/<int:id>/', EditPlanView.as_view(), name='edit-plan-id'),
    path('contact/', Contact.as_view(), name='contact'),
    path('about_app/', AboutApp.as_view(), name='about_app'),
]

jedzonko/models.py
from django.db import models

WEEK_DAYS = (
    (0, "Poniedziałek"),
    (1, "Wtorek"),
    (2, "Środa"),
    (3, "Czwartek"),
    (4, "Piątek"),
    (5, "Sobota"),
    (6, "Niedziela"),
)


class Recipe(models.Model):
    name = models.CharField(max_length=128)
    ingredients = models.CharField(max_length=512)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    preparation_time = models.IntegerField()
    preparation_method = models.TextField(default="")
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Plan(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    recipes = models.ManyToManyField(Recipe, related_name="plans", through="RecipePlan")

    def __str__(self):
        return self.name


class DayName(models.Model):
    day = models.SmallIntegerField(choices=WEEK_DAYS, default=0)


class RecipePlan(models.Model):
    meal_name = models.CharField(max_length=255)
    order = models.SmallIntegerField(null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    day = models.ForeignKey(DayName, on_delete=models.CASCADE)

    def __str__(self):
        return self.meal_name


class Page(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(default="")
    slug = models.SlugField(max_length=128)

jedzonko/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from .models import Recipe, Plan, RecipePlan, DayName, Page
from random import shuffle
from django.core.paginator import Paginator


class IndexHtmlView(View):
    def get(self, request):
        recipes = list(Recipe.objects.all())
        shuffle(recipes)

        if Page.objects.filter(slug="contact").exists():
            contact_link = "contact"
        else:
            contact_link = "#contact"

        if Page.objects.filter(slug="about_app").exists():
            about_app_link = "about_app"
        else:
            about_app_link = "#about"

        ctx = {
            "recipes_for_carousel": recipes[0:3],
            "contact_link": contact_link,
            "about_app_link": about_app_link
        }
        return render(request, "index.html", ctx)


class DashboardView(View):
    def get(self, request):
        number_of_plans = Plan.objects.count()
        number_of_recipes = Recipe.objects.count()
        latest_plan = Plan.objects.all().order_by('-created')[0]
        day_ids = RecipePlan.objects.filter(plan_id=latest_plan.id).values_list("day_id")
        recipe_plans = RecipePlan.objects.all().filter(plan_id=latest_plan).order_by("order")

        days = set()
        for day in day_ids:
            days.add(DayName.objects.get(pk=day[0]))

        ctx = {
            "number_of_plans": number_of_plans,
            "number_of_recipes": number_of_recipes,
            "latest_plan": latest_plan,
            "days": days,
            "recipe_plans": recipe_plans,
        }

        return render(request, "dashboard.html", ctx)


class RecipeIdView(View):
    def get(self, request, id):
        recipe = get_object_or_404(Recipe, id=id)
        return render(request, "app-recipe-details.html", {"recipe": recipe})

    def post(self, request, id):
        recipe = get_object_or_404(Recipe, id=id)
        if request.POST.get('like'):
            recipe.votes += 1
        else:
            recipe.votes -= 1
        recipe.save()
        return redirect('recipe-id', id=recipe.id)


class RecipeAdd(View):
    def get(self, request):
        return render(request, "app-add-recipe.html")

    def post(self, request):
        name = request.POST.get("name")
        ingredients = request.POST.get("ingredients")
        description = request.POST.get("description")
        preparation_time = request.POST.get("preparation_time")
        preparation_method = request.POST.get("preparation_method")

        if not name or not ingredients or not description or not preparation_time or not preparation_method:
            return render(request, "app-add-recipe.html", {"error": "Wypełnij poprawnie wszystkie pola"})

        Recipe.objects.create(name=name, ingredients=ingredients, description=description,
                              preparation_time=preparation_time, preparation_method=preparation_method)

        return redirect(reverse('recipes-list'))


class RecipeModify(View):
    def get(self, request, id):
        recipe = get_object_or_404(Recipe, id=id)

        if request.session.get("error"):
            request.session["error"] = False
            return render(request, "app-edit-recipe.html", {"recipe": recipe,
                                                            "error": "Wypełnij poprawnie wszystkie pola"})
        return render(request, "app-edit-recipe.html", {"recipe": recipe})

    def post(self, request, id):
        name = request.POST.get("name")
        description = request.POST.get("description")
        prep_time = int(request.POST.get("prep-time"))
        prep_method = request.POST.get("prep-method")
        ingredients = request.POST.get("ingredients")

        if name and description and prep_time and prep_method and ingredients:
            Recipe.objects.create(name=name, ingredients=ingredients, description=description,
                                  preparation_time=prep_time, preparation_method=prep_method)
            return redirect('recipes-list')

        request.session["error"] = True
        return redirect('recipe-modify', id=id)


class PlanIdView(View):
    def get(self, request, id):
        plan = get_object_or_404(Plan, id=id)
        day_ids = RecipePlan.objects.filter(plan_id=plan.id).values_list("day_id")
        recipe_plans = RecipePlan.objects.all().filter(plan_id=plan).order_by("order")

        days = set()
        for day in day_ids:
            days.add(DayName.objects.get(pk=day[0]))

        ctx = {
            "plan": plan,
            "days": days,
            "recipe_plans": recipe_plans,
        }
        return render(request, "app-details-schedules.html", ctx)


class PlanAddRecipe(View):
    def get(self, request):
        plans = Plan.objects.all().order_by("name")
        recipes = Recipe.objects.all().order_by("name")
        days = DayName.objects.all().order_by("day")

        ctx = {
            "plans": plans,
            "recipes": recipes,
            "days": days,
        }

        if request.session.get("error"):
            request.session["error"] = False
            ctx = {**ctx, "error": "Wypełnij poprawnie wszystkie pola"}
            return render(request, "app-schedules-meal-recipe.html", ctx)
        return render(request, "app-schedules-meal-recipe.html", ctx)

    def post(self, request):
        plan = Plan.objects.get(name=request.POST.get("plan"))
        meal_name = request.POST.get("name")
        recipe = Recipe.objects.get(name=request.POST.get("recipe"))
        day = DayName.objects.get(day=request.POST.get("day"))

        try:
            order = int(request.POST.get("number"))
        except ValueError:
            request.session["error"] = True
            return redirect('plan-add-recipe')

        RecipePlan.objects.create(plan=plan, order=order, meal_name=meal_name, recipe=recipe, day=day)

        if plan and meal_name and order and recipe and day:
            return redirect('plan-id', id=plan.id)

        request.session["error"] = True
        return redirect('plan-add-recipe')


class RecipesListView(View):
    def get(self, request):
        recipes_list = Recipe.objects.all().order_by("-votes", "-created")
        paginator = Paginator(recipes_list, 50)
        page = request.GET.get('page')

        recipes = paginator.get_page(page)

        ctx = {
            "recipes": recipes,
        }
        return render(request, "app-recipes.html", ctx)


class NewPlan(View):
    def get(self, reqeust):
        return render(reqeust, "app-add-schedules.html")

    def post(self, request):
        name = request.POST.get("name")
        description = request.POST.get("description")

        if name and description:
            plan = Plan.objects.create(name=name, description=description)
            return redirect('plan-id', id=plan.id)
        return render(request, "app-add-schedules.html", {"error": "Wypełnij poprawnie wszystkie pola"})


class PlansListView(View):
    def get(self, request):
        plans_list = Plan.objects.all().order_by("name")
        paginator = Paginator(plans_list, 50)
        page = request.GET.get('page')

        plans = paginator.get_page(page)

        ctx = {
            "plans": plans,
        }
        return render(request, "app-schedules.html", ctx)


class Contact(View):
    def get(self, request):
        if Page.objects.filter(slug="contact").exists():

            return render(request, "contact.html")
        else:
            return redirect(reverse('landing_page'))


class AboutApp(View):
    def get(self, request):
        if Page.objects.filter(slug="about_app").exists():

            return render(request, "about_app.html")
        else:
            return redirect(reverse('landing_page'))


class DeleteRecipeView(View):

    def get(self, request, id):
        recipe = Recipe.objects.get(id=id)
        recipeplan = RecipePlan.objects.all().filter(recipe_id=recipe)
        recipeplan.delete()
        return redirect("plan-id", id=id)

class EditPlanView(View):
    def get(self, request, id):
        plan = Plan.objects.get(id=id)
        return render(request, "app-edit-schedules.html", {"plan": plan})

    def post(self, request, id):
        name = request.POST.get("name")
        description = request.POST.get("description")

        if name and description:
            plan = Plan.objects.get(id=id)
            plan.name = name
            plan.description = description
            plan.save()
            return redirect('plan-list')
        return redirect('edit-plan-id', id=id)

jedzonko/templates/__base__.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} | Zaplanuj Jedzonko</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Open+Sans:400,600,700&amp;subset=latin-ext"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-between">
            <a href="/" class="navbar-brand main-logo main-logo-smaller">
                Zaplanuj <span>Jedzonko</span>
            </a>
         <div class="d-flex justify-content-around">
             <h4 class="text-light mr-3">Imię</h4>
             <div class="circle-div text-center"><i class="fas fa-user icon-user"></i></div>
         </div>
        </nav>
    </header>

    <section class="dashboard-section">
        <div class="row dashboard-nowrap">
                <ul class="nav flex-column long-bg">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard' %}">
                                <span>Pulpit</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "recipes-list" %}">
                                <span>Przepisy</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'plan-list' %}">
                                <span>Plany</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <!-- Podstrony związane z zarządzaniem użytkownikami
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Edytuj dane</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="">
                                <span>Zmień hasło</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Użytkownicy</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        -->
                    </ul>

            <div class="m-4 p-3 width-medium text-color-darker">

<!-- //--------------------------- page content -------------------------// -->
{% block content %}{% endblock content %}
<!-- //--------------------------- page content end ---------------------// -->

            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

jedzonko/templates/about_app.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Zaplanuj Jedzonko</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Open+Sans:400,600,700&amp;subset=latin-ext"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-around">
            <a href="/" class="navbar-brand main-logo">
                Zaplanuj <span>Jedzonko</span>
            </a>
            <ul class="nav nounderline text-uppercase">
                <!--
                <li class="nav-item ml-4">
                    <a class="nav-link color-header" href="login.html">logowanie</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link color-header" href="registration.html">rejestracja</a>
                </li>
                -->
                <li class="nav-item ml-4">
                    <a class="nav-link" href={{ about_app_link }}>o aplikacji</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link" href="{% url 'recipes-list' %}">Przepisy</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link" href={{ contact_link }}>Kontakt</a>
                </li>
            </ul>
        </nav>
    </header>
<section>
    <div>
        <div>

                <div class="col-7 ml-4">
                    <h1 class="pb-1">O aplikacji</h1>
                    <p>Aplikacja Zaplanuj Jedzonko jest scile zwiazana z ksiazka kucharska
                        napisana przez Pania Marie Iksinska. Nasza aplikacja jest dedykowana
                        zarowno czytelnikom, jak i wszystkim innym osobm zainteresowanych
                        kulinariami.
                        Zaplanuj Jedzonko pozwoli na szybkie i proste
                        planowanie codziennych zdrowych posilkow.
                    </p>
                </div>
            </div>
        </div>
    </section>


    <footer class="footer-section pt-3 pb-3">
        <div class="container text-center">
            <h5 class="text-light">Copyright <span class="footer-text-color">ZaplanujJedzonko.pl</span></h5>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

jedzonko/templates/app-add-recipe.html
{% extends "__base__.html" %}

{% block title %}Nowy przepis{% endblock %}

{% block content %}
    {% if error %}
        <!-- Form error -->
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ error }}
        </div>
        <!-- Form error -->
    {% endif %}
    <form action="" method="POST">
      {% csrf_token %}
        <div class="dashboard-content border-dashed p-3 m-4 view-height">

            <div class="mt-4 ml-4 mr-4">
                <div class="row border-bottom border-3">
                    <div class="col"><h3 class="color-header text-uppercase">Nowy
                        przepis</h3></div>
                    <div class="col d-flex justify-content-end mb-2">
                        <button type="submit"
                                class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                            Zapisz
                        </button>
                    </div>
                </div>

                <table class="table borderless">
                    <tbody>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Nazwa Przepisu</th>
                        <td class="col-7">
                            <input class="w-100 p-1" value="" name="name">
                        </td>
                    </tr>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Opis przepisu</th>
                        <td class="col-7"><textarea class="w-100 p-1"
                                                    rows="5" name="description"></textarea></td>
                    </tr>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Czas przygotowania (minuty)</th>
                        <td class="col-3">
                            <input class="p-1" type="number" value="" name="preparation_time">
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="row d-flex">
                    <div class="col-5 border-bottom border-3"><h3
                            class="text-uppercase">Sposób przygotowania</h3></div>
                    <div class="col-2"></div>
                    <div class="col-5 border-bottom border-3"><h3
                            class="text-uppercase">Składniki</h3></div>
                </div>
                <div class="row d-flex">
                    <div class="col-5 p-4">
                        <textarea class="w-100 p-1" rows="10" name="preparation_method"></textarea>
                    </div>
                    <div class="col-2"></div>

                    <div class="col-5 p-4">
                        <textarea class="w-100 p-1" rows="10" name="ingredients"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock content %}

jedzonko/templates/app-add-schedules.html
{% extends "__base__.html" %}
{% block content %}
    {% if error %}
        <!-- Form error -->
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ error }}
        </div>
        <!-- Form error -->
    {% endif %}
    <div class="schedules-content">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="dashboard-content border-dashed p-3 m-4 view-height">
                <div class="row border-bottom border-3 p-1 m-1">
                    <div class="col noPadding">
                        <h3 class="color-header text-uppercase">NOWY PLAN</h3>
                    </div>
                    <div class="col d-flex justify-content-end mb-2 noPadding">
                        <button type="submit"
                                class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                            Zapisz
                        </button>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="planName"
                           class="col-sm-2 label-size col-form-label">
                        Nazwa planu
                    </label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="planName" name="name"
                               placeholder="Nazwa planu">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="planDescription"
                           class="col-sm-2 label-size col-form-label">
                        Opis planu
                    </label>
                    <div class="col-sm-10">
                    <textarea class="form-control" rows="5" id="planDescription" name="description"
                              placeholder="Opis plany"></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block title %}{% endblock %}

jedzonko/templates/app-details-schedules.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
    <div class="dashboard-content border-dashed p-3 m-4 view-height">

        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase">SZCZEGÓŁY PLANU</h3>
            </div>
            <div class="col d-flex justify-content-end mb-2 noPadding">
                <a href="{% url "plan-add-recipe" %}"
                   class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Dodaj przepis do planu</a>
            </div>
            <div class="col d-flex justify-content-end mb-2 noPadding">
                <a href="{% url 'plan-list' %}" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Powrót</a>
            </div>
        </div>

        <div class="schedules-content">
            <div class="schedules-content-header">
                <div class="form-group row">
                    <span class="col-sm-2 label-size col-form-label">
                        Nazwa planu
                    </span>
                    <div class="col-sm-10">
                        <p class="schedules-text">{{ plan.name }}</p>
                    </div>
                </div>
                <div class="form-group row">
                    <span class="col-sm-2 label-size col-form-label">
                        Opis planu
                    </span>
                    <div class="col-sm-10">
                        <p class="schedules-text">
                            {{ plan.description }}
                        </p>
                    </div>
                </div>
            </div>

            <table class="table">
                <thead>
                <tr class="d-flex">
                    <th class="col-2">{{ days.day }}</th>
                    <th class="col-7"></th>
                    <th class="col-1"></th>
                    <th class="col-2"></th>
                </tr>
                </thead>
            </table>

            <table class="table">
                {% for day in days %}
                    <thread>
                        <tr class="d-flex">
                            <th class="col-2">{{ day.get_day_display }}</th>
                            <th class="col-8"></th>
                            <th class="col-2"></th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for recipe in recipe_plans %}
                        {% if recipe.day == day %}
                            <tr class="d-flex">
                                <td class="col-2">{{ recipe.meal_name }}</td>
                                <td class="col-8">{{ recipe.recipe }}</td>
                                <td class="col-2">
                                    <a href="{% url "recipe-id" id=recipe.recipe_id %}">
                                        <button type="button" class="btn btn-primary rounded-0">Szczegóły</button>
                                    </a>
                                    <a href="{% url "delete-recipe-id" plan_id=plan.id day_id=day.id recipe_id=recipe.recipe_id %}">
                                        <button type="button" class="btn btn-danger rounded-0">Usuń</button>
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock content %}

jedzonko/templates/app-schedules-meal-recipe.html
{% extends "__base__.html" %}
{% block title %}{% endblock %}
{% block content %}
{% if error %}
    <!-- Form error -->
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ error }}
    </div>
    <!-- Form error -->
{% endif %}
<form action="" method="POST">
{% csrf_token %}
    <div class="dashboard-content border-dashed p-3 m-4 view-height">
        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase">DODAJ PRZEPIS DO PLANU</h3>
            </div>
            <div class="col d-flex justify-content-end mb-2 noPadding">
                <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Zapisz</button>
            </div>
        </div>

        <div class="schedules-content">
            <form>
                <div class="form-group row">
                    <label for="choosePlan"
                           class="col-sm-2 label-size col-form-label">
                        Wybierz plan
                    </label>
                    <div class="col-sm-3">
                        <select class="form-control" id="choosePlan" name="plan">
                            {% for plan in plans %}
                                <option value="{{ plan }}">{{ plan }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 label-size col-form-label">
                        Nazwa posiłku
                    </label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" value="" id="name" name="name"
                               placeholder="Nazwa posiłku">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="number" class="col-sm-2 label-size col-form-label">
                        Numer posiłku
                    </label>
                    <div class="col-sm-3">
                        <input type="number" class="form-control" id="number" name="number"
                               placeholder="Numer posiłku">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="recipe" class="col-sm-2 label-size col-form-label">
                        Przepis
                    </label>
                    <div class="col-sm-5">
                        <select class="form-control" id="recipe" name="recipe">
                            {% for recipe in recipes %}
                                <option value="{{ recipe }}">{{ recipe }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="day" class="col-sm-2 label-size col-form-label">
                        Dzień
                    </label>
                    <div class="col-sm-3">
                        <select class="form-control" id="day" name="day">
                            {% for day in days %}
                                <option value="{{ day.day }}">{{ day.get_day_display }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</form>
{% endblock content %}